### ISSUE TITLE
Don't know if I'm doing the .env file correctly. 

### ISSUE THREAD

**Issue by tyao117** [urbanspr1nter/emma#22]
Don't know if I'm doing the .env file correctly. Here is the file for ".env"
```
EnvironmentName=development
AzureServiceBusConnectionString=
AzureServiceBusQueue=
APPINSIGHTS_INSTRUMENTATIONKEY=
APPINSIGHTS_PORTALINFO=Node
AzureStorageAccount=
AzureStorageAccountKey=
AzureStorageBlobContainer=
LogsDirectory=/log
```
I'm running it this way:
```
npm install dotenv
npm install
npm run start
```
Here is the log for the program:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle emma@1.0.0~prestart: emma@1.0.0
6 info lifecycle emma@1.0.0~start: emma@1.0.0
7 verbose lifecycle emma@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle emma@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/blazer/Documents/emma/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle emma@1.0.0~start: CWD: /home/blazer/Documents/emma
10 silly lifecycle emma@1.0.0~start: Args: [ '-c', 'node --max-old-space-size=2048 index.js' ]
11 silly lifecycle emma@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle emma@1.0.0~start: Failed to exec start script
13 verbose stack Error: emma@1.0.0 start: `node --max-old-space-size=2048 index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid emma@1.0.0
15 verbose cwd /home/blazer/Documents/emma
16 verbose Linux 4.14.53-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error emma@1.0.0 start: `node --max-old-space-size=2048 index.js`
22 error Exit status 1
23 error Failed at the emma@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tyao117** [comment]
apparently, some .env are required. here are the logs of today's run. Will try with Azure if this keeps failing.  
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle emma@1.0.0~prestart: emma@1.0.0
6 info lifecycle emma@1.0.0~start: emma@1.0.0
7 verbose lifecycle emma@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle emma@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/blazer/Documents/emma/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle emma@1.0.0~start: CWD: /home/blazer/Documents/emma
10 silly lifecycle emma@1.0.0~start: Args: [ '-c', 'node --max-old-space-size=2048 index.js' ]
11 silly lifecycle emma@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle emma@1.0.0~start: Failed to exec start script
13 verbose stack Error: emma@1.0.0 start: `node --max-old-space-size=2048 index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:304:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid emma@1.0.0
15 verbose cwd /home/blazer/Documents/emma
16 verbose Linux 4.14.53-1-MANJARO
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.6.0
19 verbose npm  v6.1.0
20 error code ELIFECYCLE
21 error errno 1
22 error emma@1.0.0 start: `node --max-old-space-size=2048 index.js`
22 error Exit status 1
23 error Failed at the emma@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by urbanspr1nter** [comment]
Thanks this is a legit bug. AppInsights from Azure should not be required.

**Comment by urbanspr1nter** [comment]
This has been fixed with the latest commit.

**Comment by tyao117** [comment]
the site is now working: 
![image](https://user-images.githubusercontent.com/13957424/42914247-32fcd8a2-8aae-11e8-9b6a-fe04717b4041.png)
Closing the issue
